require('dotenv').config()

const nodemailer = require('nodemailer');
const GMAIL_USER = process.env.GMAIL_USER
const GMAIL_PASSWORD = process.env.GMAIL_PASSWORD

  
let mailTransporter = nodemailer.createTransport({
    host: "smtp.free.fr",
    port: 25,
    auth: {
      user: "chefmenu@free.fr", //generated by Mailtrap
      pass: "chefmenu13456" //generated by Mailtrap
    }
});
module.exports = {
    sendMail : (to, subject, text) => {
        let mailDetails = {
            from: "chefmenu@free.fr",
            to,
            subject,
            text
        };
          
        mailTransporter.sendMail(mailDetails, function(err, data) {
            if(err) {
                console.log(err,GMAIL_USER,GMAIL_PASSWORD);
            } else {
                console.log('Email sent successfully');
            }
        });
    }

}