require('dotenv').config()

const nodemailer = require('nodemailer');
const SMTP_USER = process.env.SMTP_USER
const SMTP_PASSWORD = process.env.SMTP_PASSWORD

  
let mailTransporter = nodemailer.createTransport({
    host: "smtp.free.fr",
    port: 25,
    auth: {
      user: SMTP_USER, //generated by Mailtrap
      pass: SMTP_PASSWORD //generated by Mailtrap
    }
});
module.exports = {
    sendMail : (to, subject, text) => {
        let mailDetails = {
            from: SMTP_USER,
            to,
            subject,
            text
        };
          
        mailTransporter.sendMail(mailDetails, function(err, data) {
            if(err) {
                console.log(err,GMAIL_USER,GMAIL_PASSWORD);
            } else {
                console.log('Email sent successfully');
            }
        });
    }

}